### ISSUE TITLE
[PE-D][Tester B] Unable to proceed after data corruption in question file

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-4/tp#157]
![image.png](https://raw.githubusercontent.com/NigelYeoTW/ped/main/files/9fd6fa8f-dfdf-4b00-a10d-6223d6af2df6.png)

Unable to select the minimal questions of 1 after editing the data file

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: NigelYeoTW/ped#14

**Comment by shaunngoh** [comment]
should we add into the developerGuide regarding this issue that they should not touch Questions.txt file?
